name: youtube
version: 1.0
api: 3.0.0
author: V3rsucht, WasIstMarcel
main: youtube\Main

commands:
  yt:
    description: "§4YoutubeInfo"
    usage: "/yt"
    permission: "yt.info"
  discord:
    description: "§4Discord-Server"
    usage: "/discord"
  kanal:
    description: "§4Unser YT Kanal"
    usage: "/kanal"
  author:
    description: "§4Kanal"
    usage: "/author"

permissions:
  yt.info:
    default: op
    description: "Erlaubt es dem Spieler das YouTube Setup durchzuführen!!!"
